version: "3.9"
services:
  my-flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=myshop
      - FLASK_ENV=development